<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Airports;

/**
 * AirportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportsRepository extends EntityRepository
{

    /**
     * @return Airports[] array
     */
    public function getAirportsData(){

        $airportsArray = [];
        $qb = $this->createQueryBuilder('a');

        $airports = $qb->getQuery()->getResult();

        /** @var Airports $airport */
        foreach($airports as $airport){
            $airportsArray[$airport->getAirportIcao()] = $airport;
        }

        return $airportsArray;

    }

}
