<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\MonitoredAirport;

/**
 * AirportsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitoredAirportRepository extends EntityRepository
{
    /**
     * @param int $alternate
     * @param $season
     * @return \Doctrine\ORM\Query
     */
    public function getSeasonActiveAirports($alternate = 0, $season)
    {
        $qb = $this->createQueryBuilder('a');
        if ($season == 0) {
            $qb->where('a.activeWinter = 1');
            $qb->andWhere('a.alternateWinter = :alternate');
        } elseif ($season == 1) {
            $qb->where('a.activeSummer = 1');
            $qb->andWhere('a.alternateSummer = :alternate');
        }

        $qb->setParameter('alternate', $alternate);
        
        $airportsQuery = $qb->getQuery();

        return $airportsQuery;
    }

    /**
     * @param bool      $season
     * @param \DateTime $referenceTime
     * 
     * @return \AppBundle\Entity\MonitoredAirport[]
     */

    /**
     * @param bool      $season
     * @param \DateTime $referenceTime
     * @return \Doctrine\ORM\Query
     */
    public function getAirportsWithOldMetar($season, $referenceTime)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.rawMetarDateTime < :datetime')
            ->orWhere('a.rawMetarDateTime IS NULL');

        if ($season == 0) {
            $qb->andWhere('a.activeWinter = 1');
            $qb->andWhere('a.alternateWinter = 0');
        } elseif ($season == 1) {
            $qb->andWhere('a.activeSummer = 1');
            $qb->andWhere('a.alternateSummer = 0');
        }

        $qb->setParameter('datetime', $referenceTime);

        $airportsQuery = $qb->getQuery();
        
        return $airportsQuery;
    }
    
}
